--- #YAML:1.0
name:                Net-Packet
version:             3.26
abstract:            a framework to easily send and receive frames from layer 2 to layer 7
license:             artistic
author:              
    - GomoR <perl@gomor.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Bit::Vector:                   0
    Class::Gomor:                  1.00
    Net::IPv6Addr:                 0
    Net::Libdnet:                  0
    Net::Pcap:                     0.12
    Net::Write:                    1.00
    Socket6:                       0
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
