--- #YAML:1.0
name:               Net-Packet
version:            3.27
abstract:           a framework to easily send and receive frames from layer 2 to layer 7
author:
    - GomoR <gomor-cpan_at_gomor.org>
license:            artistic
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Bit::Vector:    0
    Class::Gomor:   1.00
    Net::IPv4Addr:  0
    Net::IPv6Addr:  0
    Net::Libdnet:   0
    Net::Pcap:      0.12
    Net::Write:     1.00
    Socket6:        0
    Time::HiRes:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
